from __future__ import annotations

from html import escape
from typing import Dict, Protocol

from .models import AppSpec


class CodeGenerator(Protocol):
    def generate(self, spec: AppSpec) -> Dict[str, str]:
        """Generate project files from a validated app specification."""


class HeuristicCodeGenerator:
    """Safe MVP generator that creates static files without executing them."""

    def generate(self, spec: AppSpec) -> Dict[str, str]:
        return {
            "index.html": self._index_html(spec),
            "styles.css": self._styles_css(),
            "app.js": self._app_js(),
            "README.md": self._readme(spec),
        }

    @staticmethod
    def _index_html(spec: AppSpec) -> str:
        title = escape(spec.name)
        description = escape(f"A {spec.app_type} generated by FizFox.")
        pages = "\n".join(
            f'          <a href="{escape(page.route)}">{escape(page.name)}</a>'
            for page in spec.pages
        ) or '          <a href="/">Home</a>'
        features = "\n".join(
            f"          <li>{escape(feature)}</li>" for feature in spec.features
        ) or "          <li>Responsive layout</li>"
        return f'''<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{description}">
    <title>{title}</title>
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
    <header class="site-header">
      <a class="brand" href="/">{title}</a>
      <nav aria-label="Primary navigation">
{pages}
      </nav>
    </header>
    <main>
      <section class="hero">
        <p class="eyebrow">Built with FizFox</p>
        <h1>{title}</h1>
        <p>{description}</p>
        <button type="button" id="primary-action">Get started</button>
      </section>
      <section class="content" aria-labelledby="features-heading">
        <h2 id="features-heading">Features</h2>
        <ul>
{features}
        </ul>
      </section>
    </main>
    <footer>Generated by FizFox.</footer>
    <script src="app.js"></script>
  </body>
</html>
'''

    @staticmethod
    def _styles_css() -> str:
        return '''* { box-sizing: border-box; }
:root { font-family: -apple-system, BlinkMacSystemFont, "SF Pro Text", Inter, system-ui, sans-serif; color: #17131f; background: #faf9ff; }
body { margin: 0; min-height: 100vh; background: linear-gradient(145deg, #ffffff 0%, #f6f2ff 100%); }
.site-header { display: flex; align-items: center; justify-content: space-between; gap: 24px; padding: 20px clamp(20px, 5vw, 72px); background: rgba(255,255,255,.78); border-bottom: 1px solid rgba(115,86,232,.12); backdrop-filter: blur(18px); }
.brand { color: inherit; font-weight: 750; text-decoration: none; letter-spacing: -.03em; }
nav { display: flex; flex-wrap: wrap; gap: 16px; } nav a { color: #665f70; text-decoration: none; } nav a:hover { color: #7356e8; }
main { width: min(100% - 40px, 980px); margin: 0 auto; }
.hero { padding: 96px 0 72px; text-align: center; } .eyebrow { color: #7356e8; font-weight: 700; }
h1 { margin: 12px 0; font-size: clamp(48px, 9vw, 88px); line-height: .95; letter-spacing: -.065em; }
.hero p:not(.eyebrow) { max-width: 650px; margin: 20px auto 30px; color: #6e6878; font-size: 19px; line-height: 1.6; }
button { border: 0; border-radius: 999px; padding: 14px 22px; background: #7356e8; color: white; font: inherit; font-weight: 700; cursor: pointer; }
.content { padding: 28px; border: 1px solid rgba(115,86,232,.12); border-radius: 28px; background: rgba(255,255,255,.7); box-shadow: 0 20px 60px rgba(57,37,108,.08); }
li { margin: 10px 0; color: #5f586b; } footer { padding: 56px 0; text-align: center; color: #8a8394; }
@media (max-width: 640px) { .site-header { align-items: flex-start; flex-direction: column; } .hero { padding-top: 68px; } .content { padding: 22px; } }
'''

    @staticmethod
    def _app_js() -> str:
        return '''const action = document.querySelector("#primary-action");
if (action) {
  action.addEventListener("click", () => {
    action.textContent = "Ready to build";
  });
}
'''

    @staticmethod
    def _readme(spec: AppSpec) -> str:
        pages = "\n".join(f"- `{page.route}` — {page.name}" for page in spec.pages) or "- `/` — Home"
        features = "\n".join(f"- {feature}" for feature in spec.features) or "- Responsive layout"
        return f'''# {spec.name}

Generated by FizFox's deterministic MVP code generator.

## App type

{spec.app_type}

## Pages

{pages}

## Features

{features}
'''
